updated change batch button
organization-x/hippo2-frontend pull request #133
Opened 2022-08-10 04:26 UTC by TheFeesh

![image](https://user-images.githubusercontent.com/43019971/183815788-cc495310-3140-45cb-8086-16ecf24d33a4.png)

2022-08-10 04:40 UTC, AlexanderZhou39 requested changes

2022-08-10 04:40 UTC, AlexanderZhou39 commented on src/pages/dashboard/screens/courseDetails.jsx
> +						<p className="mb-5"><b className="font-semibold">{course.batch.name}: </b>{course.batch.start_date} - {course.batch.end_date}, {course.batch.start_time} - {course.batch.end_time} {course.batch.
add `Batch` before the batch name

2022-08-10 04:40 UTC, AlexanderZhou39 commented on src/pages/dashboard/screens/courseDetails.jsx
>  							<Button bgColor="white" txtColor="black" className="w-2/3 py-1">Cancel Your Course</Button>
for the buttons, replace `w-2/3` with `w-full md:w-2/3`

2022-08-10 04:59 UTC, TheFeesh commented on src/pages/dashboard/screens/courseDetails.jsx
> +						<p className="mb-5"><b className="font-semibold">{course.batch.name}: </b>{course.batch.start_date} - {course.batch.end_date}, {course.batch.start_time} - {course.batch.end_time} {course.batch.
wdym?

2022-08-11 01:13 UTC, AlexanderZhou39 approved these changes

2022-08-11 01:14 UTC, merged