/user/details page and account settings page with getInformation.js tweaks
organization-x/hippo2-frontend pull request #51
Opened 2022-07-02 01:35 UTC by RickleAndMortimer

2022-07-02 03:19 UTC, AlexanderZhou39 requested changes
Some styling changes and dob handling. Everything else is great

2022-07-02 03:19 UTC, AlexanderZhou39 commented on src/pages/userInformation/userDetails.js
> +        </div>
Details page should not have email. If the user is a parent, it should also not display dob field. Some other stuff also doesn't really match with the figma
![Screen Shot 2022-07-01 at 8 10 29 PM](https://user-images.githubusercontent.com/66284119/176984640-4e958916-9bc9-4610-84aa-2a52897da32c.png)

2022-07-02 03:19 UTC, AlexanderZhou39 commented on src/pages/dashboard/account-settings.js
> +		    <GetInformation key={i} headerText={`${groupUser.first_name}'s Profile`} {...groupUser} className="md:w-1/4 bg-white rounded-xl"/>
w-1/4 is too small. It gets really squeezed on tablets for example
![Screen Shot 2022-07-01 at 8 17 42 PM](https://user-images.githubusercontent.com/66284119/176984799-9e51f5c3-2a32-4880-b08f-4f65ae6870a8.png)

2022-07-06 03:05 UTC, AlexanderZhou39 requested changes
Some last additional things to change.

2022-07-06 03:05 UTC, AlexanderZhou39 commented on src/pages/userInformation/userDetails.js
> +			 }
use `handleUserInitiation` method from `useAuth`. That will update the user's info on the backend as well. 

Do not navigate directly to /invite. `handleUserInitiation` will handle that. for now just
```js
const location = useLocation();
const origin = location.state?.from?.pathname || '/';

// onsubmit
auth.handleUserInitiation(data.first_name, data.last_name, data.dob, data.phone, origin);
```

also, change all of your names from `snake_case` to `camelCase` since this is javascript. i.e. `first_nam` -> `firstName`

2022-07-06 03:05 UTC, AlexanderZhou39 commented on src/pages/userInformation/getInformation.js
> +        sendReq(updateUrl, options).then((res) => {
use `auth.autoAuthReq` since this endpoint requires authentication

2022-07-06 03:19 UTC, AlexanderZhou39 commented on src/pages/userInformation/getInformation.js
> +        }
remove all the "onSubmit" logic for now and just make it an empty function. I'll need to make a method in authentication.js for updating user info. Just directly updating the backend won't update the frontend records in the auth provider.

2022-07-06 22:29 UTC, neverabsolute approved these changes
noice.

2022-07-06 22:29 UTC, AlexanderZhou39 approved these changes

2022-07-06 22:30 UTC, merged